version: "3.9"
services:
  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=conway
      - POSTGRES_USER=brahayan
      - POSTGRES_PASSWORD=dev

volumes:
  db-data: