version: "3.9"
services:
  database:
    image: postgres:13-alpine
    volumes:
      - data-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=framework-db
      - POSTGRES_USER=brahayan
      - POSTGRES_PASSWORD=development

volumes:
  data-db:  