#!/usr/bin/env bash

bin_dir=$(dirname $(readlink -f $0))
project_dir=$(dirname "$bin_dir")

cd "$project_dir"
# Some tests need JAVA_HOME. Unfortunately, the archlinux distribution
# doesn't set it automatically but instead has a mechanism to select
# the current java version (archlinux-java) using the link. So this
# link will contain the version of java used
if [ -f /etc/os-release ]; then
    source /etc/os-release
    if [[ "$ID_LIKE" == "arch" ]]; then
        export JAVA_HOME=/usr/lib/jvm/default
    fi
fi

lein test
