CREATE DATABASE cli_chat;
GRANT ALL PRIVILEGES ON DATABASE cli_chat TO postgres;

DROP DATABASE IF EXISTS cli_chat_test;
CREATE DATABASE cli_chat_test;
GRANT ALL PRIVILEGES ON DATABASE cli_chat_test TO postgres;
