version: "3.3"
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=cli_chat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data:
