name: clj-kondo checks

on: [push]

jobs:
  self-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint src # TODO: lint tests, examples
        github_token: ${{ secrets.GITHUB_TOKEN }}
