name: Clojure CI

on:
  push:
    branches: '!main'
  pull_request:
    branches: [ main ]

jobs:
  check-examples:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@5.0
      with:
        cli: 1.11.1.1113
        lein: 2.9.8
      
    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('project.clj') }}
        restore-keys: |
          m2-

    - name: Checking examples
      run: ./example-tests.sh
