name: Clojure CI

on:
  push:
    branches: '!main'
  pull_request:
    branches: [ main ]

jobs:
  check-examples:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@9.4
      with:
        # Install just one or all simultaneously
        # The value must indicate a particular version of the tool, or use 'latest'
        # to always provision the latest version
        cli: 1.11.1.1155              # Clojure CLI based on tools.deps
        lein: 2.9.1                  # Leiningen
        bb: 0.7.8                    # Babashka
      
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('project.clj') }}
        restore-keys: |
          m2-

    - name: Checking examples
      run: ./example-tests.sh
