name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('project.clj') }}
        restore-keys: |
          m2-

    - name: Run tests
      run: lein test
