name: Clojure CI

on:
  push:
    branches: '!main'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.1
      with:
        cli: '1.10.2.796'
      
    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('project.clj') }}
        restore-keys: |
          m2-

    - name: Run cljstyle
      run: lein cljstyle check src test

    - name: Run tests
      run: lein test
